### ISSUE TITLE
Smite Chaos Option

### ISSUE THREAD

**Issue by Grawul** [alterasc/MicroscopicContentExpansion#1]
Hi, I like playing an Antipaladin since this is a nice addition for my evil Lich playthrough. But the problem lies with Smite Good, which is 100% correct from the rulebook, but also very useless in the Wrath Setting where there are mostly evil enemies.
My suggestion is if you could add an archtype with Smite Chaos instead of Smite Good. For example in the CotW Mod for Kingmaker there were several Archtypes with different Smites.

**Comment by alterasc** [comment]
Hi,

I understand the problem, but my view is this:  
Antipaladin is strict anti-good class. Picking it in a anti-demon campaign means you understand that you're intentionally taking disadvantaged class. Same as if you make Evil Inquisitor Faith Hunter who gets Sworn Enemy - Good. 

Another reason - in WotR Smite Chaos with absolute majority of enemies being CE is same as Smite Evil. Meaning that archetype with Smite Chaos would make other archetypes look nearly pointless. Tyrant is already a bit better (because of axiomatic weapon bond and protection from chaos spells), making it better by a mile and a half - no. I know that CotW changed Tyrant to have Smite Chaos, but won't do that.

I know existence of Blighted Myrmidon (Smite Nature) and Insinuator (Smite Impudence), but first is entirely pointless in WotR, and second I just personally don't like.  

Final answer - apologies, Smite Chaos is not coming. My stance on this matter is firm and very unlikely to change. 
You can either dip Hellknight, or try to focus Antipaladin features that do work against demons.
